name: Build+Upload
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env: 
  PROJECT: ${{ 'Graveyard' }}

jobs:
  build-and-upload:
    runs-on: windows-latest      
    steps:   
      - uses: actions/checkout@v3.5.2 # https://github.com/marketplace/actions/checkout
      - name: Get Head Commit Message
        id: get_head_commit
        shell: pwsh
        run: |
          $Message = git log --format=%B -n 1 HEAD
          Write-Output "title=$($Message | Select -First 1)" >> $Env:GITHUB_OUTPUT
          $Body = $Message | Select -Skip 1
          Write-Output "body=$Body" >> $Env:GITHUB_OUTPUT
          $Body | Out-File Release.md
      - uses: microsoft/setup-msbuild@v1.3.1 # https://github.com/marketplace/actions/setup-msbuild
      - uses: NuGet/setup-nuget@v1.2.0 # https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions
      - run: .\scripts\update-libraries.ps1
      - run: nuget restore "${{ env.PROJECT }}.sln"
      - id: set_version
        run: |
          $build = 2000 + $env:GITHUB_RUN_NUMBER
          $buildVersion = .\scripts\assembly-version.ps1 -project "${{ env.PROJECT }}" -build $build -overrideVersion ${{ github.ref }}
          echo "buildVersion=$buildVersion" >> $env:GITHUB_OUTPUT
        # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
        # https://stackoverflow.com/a/74377542/146360
      - run: msbuild.exe "${{ env.PROJECT }}.sln" /p:platform="x86" /p:configuration="Release"
      - id: name_zip
        run: |
          $zipName = "${{ env.PROJECT }}-v${{ steps.set_version.outputs.buildVersion }}"
          echo "zipName=$zipName" >> $env:GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4.6.2 # https://github.com/marketplace/actions/upload-a-build-artifact
        with:
          name: "${{ steps.create_zip.outputs.zipName }}"
          path: |
            .\${{ env.PROJECT }}\bin\x86\Release\${{ env.PROJECT }}.dll 
            .\${{ env.PROJECT }}\bin\x86\Release\*-*
